### ISSUE TITLE
Linker error on macOS

### ISSUE THREAD

**Issue by jeremiedbb** [conda-forge/cctools-and-ld64-feedstock#11]
Possible regression in compilers 1.0.4.
Compiling a simple C program fails at link time. Used to work in 1.0.3.

 Here's the C code "test.c":
```C
#include <stdio.h>

int main(void){
    printf("hello world");
}
```
`clang test.c` gives the following error:
```
ld: library not found for -lSystem
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
I checked I'm using clang from the compilers package:
```
$ which clang
path/to/conda_env/bin/clang
```

Possibly due to the bump of clang version (8 -> 9) ?

**Comment by isuruf** [comment]
I've marked the latest builds as broken. Can you send a PR adding a test?

**Comment by isuruf** [comment]
Btw, can you run dtrace on the command and post the output?

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/cctools-and-ld64-feedstock/pull/12 . Can someone send a PR to my PR with a test using a newer SDK? You'll have to download a new SDK in the test and set `CONDA_BUILD_SYSROOT` to that.

**Comment by isuruf** [comment]
Ping on this.
