### ISSUE TITLE
Fix ld64 patch

### ISSUE THREAD

**Issue by beckermr** [conda-forge/cctools-and-ld64-feedstock#16]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

We need to add back a patch according to this comment here

https://github.com/conda-forge/slycot-feedstock/pull/22#issuecomment-578435575

**Comment by beckermr** [comment]
Cc @isuruf for viz

Also @mbargull

**Comment by isuruf** [comment]
cc @davidbrochart, we missed https://github.com/conda-forge/cctools-and-ld64-feedstock/blob/aa02336d34387762dfb2cebdd843a73d7b6ce465/recipe/530-ld64-add-conda-specific-env-vars-to-modify-lib-search-paths.patch#L48-L49 in the patch
